"""Read-only filesystem protocol for QMT built-in Python snapshots."""

from .constants import (
    BRIDGE_VERSION,
    ENVIRONMENT_ID,
    LATEST_SNAPSHOT_RELATIVE_PATH,
    PROVIDER_ID,
    SCHEMA_VERSION,
    TEMP_SNAPSHOT_RELATIVE_PATH,
)
from .errors import (
    AccountIdentityMismatchError,
    DuplicateSequenceError,
    IncompleteAtomicWriteError,
    InvalidSnapshotValueError,
    MalformedSnapshotError,
    MissingSnapshotError,
    OrderSubmissionNotEnabledError,
    QmtBuiltinBridgeError,
    ReadOnlyBridgeError,
    RegressingSequenceError,
    SequenceError,
    StaleSnapshotError,
    UnsupportedSchemaError,
)
from .reader import QmtBuiltinBridgeReader, SequenceTracker, snapshot_from_mapping
from .readonly import QmtBuiltinReadOnlyBridge
from .records import (
    AccountRecord,
    FailureInfo,
    OrderRecord,
    PositionRecord,
    QmtBridgeSnapshot,
    QueryStatus,
    QueryStatusBundle,
    ReadOnlySafetyState,
    RuntimeMetadata,
    TradeRecord,
    serialize_snapshot,
    snapshot_to_mapping,
)
from .redaction import (
    ACCOUNT_BINDING_KEY_BYTES,
    MAX_ACCOUNT_ID_UTF8_BYTES,
    AccountBindingKeyError,
    AccountIdentityRedactionError,
    bounded_provider_metadata,
    is_redacted_account_identity,
    is_sensitive_field_name,
    redact_account_identity,
    validate_account_binding_key,
)


__all__ = [
    "ACCOUNT_BINDING_KEY_BYTES",
    "AccountBindingKeyError",
    "AccountIdentityMismatchError",
    "AccountIdentityRedactionError",
    "AccountRecord",
    "BRIDGE_VERSION",
    "DuplicateSequenceError",
    "ENVIRONMENT_ID",
    "FailureInfo",
    "IncompleteAtomicWriteError",
    "InvalidSnapshotValueError",
    "LATEST_SNAPSHOT_RELATIVE_PATH",
    "MalformedSnapshotError",
    "MAX_ACCOUNT_ID_UTF8_BYTES",
    "MissingSnapshotError",
    "OrderRecord",
    "OrderSubmissionNotEnabledError",
    "PROVIDER_ID",
    "PositionRecord",
    "QmtBridgeSnapshot",
    "QmtBuiltinBridgeError",
    "QmtBuiltinBridgeReader",
    "QmtBuiltinReadOnlyBridge",
    "QueryStatus",
    "QueryStatusBundle",
    "ReadOnlyBridgeError",
    "ReadOnlySafetyState",
    "RegressingSequenceError",
    "RuntimeMetadata",
    "SCHEMA_VERSION",
    "SequenceError",
    "SequenceTracker",
    "StaleSnapshotError",
    "TEMP_SNAPSHOT_RELATIVE_PATH",
    "TradeRecord",
    "UnsupportedSchemaError",
    "bounded_provider_metadata",
    "is_redacted_account_identity",
    "is_sensitive_field_name",
    "redact_account_identity",
    "serialize_snapshot",
    "snapshot_from_mapping",
    "snapshot_to_mapping",
    "validate_account_binding_key",
]
