"""Contracts for point-in-time announcement intelligence."""

from __future__ import annotations

ANNOUNCEMENT_EVENT_COLUMNS = (
    "event_id",
    "source",
    "source_type",
    "title",
    "content",
    "announcement_category",
    "provider_announcement_category",
    "content_source",
    "content_quality_status",
    "content_quality_reason",
    "content_quality_evidence",
    "content_char_count",
    "content_retrieval_status",
    "content_retrieval_error",
    "full_text_available",
    "content_hash",
    "content_cache_key",
    "content_cache_schema_version",
    "content_classifier_version",
    "content_truncated",
    "max_input_chars",
    "publish_time",
    "publish_time_precision",
    "first_available_time",
    "first_available_time_derivation",
    "ingestion_time",
    "affected_symbols",
    "affected_industries",
    "affected_concepts",
    "source_url",
    "source_identifier",
    "raw_content_hash",
    "deduplication_key",
    "lineage_observed",
    "lineage_derived",
    "lineage_approximated",
    "lineage_unavailable",
    "data_quality_flags",
)
