"""A-share securities-firm-style information layer schemas and normalizers."""

from quantpilot_core.information_layer.contracts import (
    ANNOUNCEMENT_EVENTS_COLUMNS,
    CONCEPT_MEMBERSHIPS_COLUMNS,
    DIVIDEND_RECORDS_COLUMNS,
    FUND_HOLDINGS_COLUMNS,
    MACRO_POLICY_EVENTS_COLUMNS,
    MARGIN_TRADING_SNAPSHOTS_COLUMNS,
    MONEYFLOW_SNAPSHOTS_COLUMNS,
    NEWS_EVENTS_COLUMNS,
    NORTHBOUND_HOLDINGS_COLUMNS,
    SHAREHOLDER_SNAPSHOTS_COLUMNS,
    SOCIAL_SENTIMENT_EVENTS_COLUMNS,
    STABILIZATION_FLOW_CLUES_COLUMNS,
    VALUATION_SNAPSHOTS_COLUMNS,
)
from quantpilot_core.information_layer.normalization import (
    normalize_announcement_events_frame,
    normalize_concept_memberships_frame,
    normalize_dividend_records_frame,
    normalize_fund_holdings_frame,
    normalize_macro_policy_events_frame,
    normalize_margin_trading_snapshots_frame,
    normalize_moneyflow_snapshots_frame,
    normalize_news_events_frame,
    normalize_northbound_holdings_frame,
    normalize_shareholder_snapshots_frame,
    normalize_social_sentiment_events_frame,
    normalize_stabilization_flow_clues_frame,
    normalize_valuation_snapshots_frame,
)

__all__ = [
    "ANNOUNCEMENT_EVENTS_COLUMNS",
    "CONCEPT_MEMBERSHIPS_COLUMNS",
    "DIVIDEND_RECORDS_COLUMNS",
    "FUND_HOLDINGS_COLUMNS",
    "MACRO_POLICY_EVENTS_COLUMNS",
    "MARGIN_TRADING_SNAPSHOTS_COLUMNS",
    "MONEYFLOW_SNAPSHOTS_COLUMNS",
    "NEWS_EVENTS_COLUMNS",
    "NORTHBOUND_HOLDINGS_COLUMNS",
    "SHAREHOLDER_SNAPSHOTS_COLUMNS",
    "SOCIAL_SENTIMENT_EVENTS_COLUMNS",
    "STABILIZATION_FLOW_CLUES_COLUMNS",
    "VALUATION_SNAPSHOTS_COLUMNS",
    "normalize_announcement_events_frame",
    "normalize_concept_memberships_frame",
    "normalize_dividend_records_frame",
    "normalize_fund_holdings_frame",
    "normalize_macro_policy_events_frame",
    "normalize_margin_trading_snapshots_frame",
    "normalize_moneyflow_snapshots_frame",
    "normalize_news_events_frame",
    "normalize_northbound_holdings_frame",
    "normalize_shareholder_snapshots_frame",
    "normalize_social_sentiment_events_frame",
    "normalize_stabilization_flow_clues_frame",
    "normalize_valuation_snapshots_frame",
]
